In [268]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
from sklearn import tree

In [269]:
df = pd.read_csv('AB.csv', na_values='?')
df.dropna(inplace=True)
df2 = pd.read_csv('AB.csv', na_values='?')
df2.dropna(inplace=True)

In [270]:
def change_status(Satus):
    if Satus == 'Operating':
        return 1;
    else :
        return 0;

In [271]:
def change_category(Categories):
    if Categories == 'Technology':
        return 0;
    elif Categories == 'Service_Ind':
        return 1;
    elif Categories == 'E-Commerce':
        return 2;
    elif Categories == 'Curated_Web':
        return 3;
    elif Categories == 'Advertising':
        return 4;
    elif Categories == 'Education':
        return 5;
    elif Categories == 'Finance':
        return 6;
    elif Categories == 'Fashion':
        return 7;
    elif Categories == 'Medical':
        return 8;

In [272]:
def change_funding(Amounts_raised_in_different_funding_rounds):
    if Amounts_raised_in_different_funding_rounds < 1:
        return 'zero'
    elif Amounts_raised_in_different_funding_rounds >1 :
        return Amounts_raised_in_different_funding_rounds;
#    elif Amounts_raised_in_different_funding_rounds < 100000 :
#        return 'Extremely_Low'
#    elif Amounts_raised_in_different_funding_rounds < 500000 :
#        return 'Low'
#    elif Amounts_raised_in_different_funding_rounds < 1000000 :
#        return 'medium'
#    elif Amounts_raised_in_different_funding_rounds < 5000000 :
 #       return 'High'
#    else:
#        return 'Extremely_High'

In [273]:
df['Satus'] = df['Satus'].apply(change_status)
df2['Satus'] = df2['Satus'].apply(change_status)
df2['Amounts_raised_in_different_funding_rounds'] = df['Amounts_raised_in_different_funding_rounds'].apply(change_funding)
#df['YCombinatorYear'] = df['YCombinatorYear'].apply(change_year)
df['Categories'] = df['Categories'].apply(change_category)
df3 = df[df2.Amounts_raised_in_different_funding_rounds != 'zero' ]
df2.drop(['Company'], axis=1, inplace=True)
df3.drop(['Company', 'HeadquartersCity'], axis=1, inplace=True)
df3

Satus  Amounts_raised_in_different_funding_rounds  Categories  \
0        1                                     1200000           2   
1        1                                     3000000           2   
2        1                                     7300000           1   
3        0                                     2000000           0   
4        1                                     1714000           6   
6        1                                     2400000           1   
7        1                                     3800000           1   
8        0                                     1300000           3   
9        0                                      740000           3   
10       1                                      535000           6   
11       1                                      750000           1   
12       1                                     1800000           3   
13       1                                     9400000           3   
14       1                                     2800000           0   
15       1                                     2400000           0   
19       1                                     2500000           1   
20       1                                     2800000           6   
21       1                                    11200000           0   
22       1                                     1200000           5   
23       1                                    39800000           0   
24       1                                      700000           6   
25       1                                     2380000           8   
26       1                                     1100000           4   
27       1                                   794820000           1   
28       0                                      875000           2   
29       1                                     5200000           6   
30       0                                    18250000           0   
31       1                                    11800000           6   
32       1                                     9720000           0   
33       0                                      500000           6   
..     ...                                         ...         ...   
648      1                                     2000000           2   
649      1                                     1800000           2   
651      1                                     1300000           2   
652      0                                      890000           2   
654      1                                     6600000           2   
655      1                                     1200000           2   
656      1                                     2000000           2   
658      1                                      784000           2   
659      1                                      100000           2   
661      1                                     2000000           2   
662      1                                     5000000           2   
664      1                                     4777000           2   
665      1                                     6830000           2   
666      0                                     3000000           2   
668      1                                    19700000           2   
670      1                                     1670000           2   
671      1                                      920000           2   
672      0                                    39106000           2   
673      1                                      750000           2   
674      1                                       50000           2   
675      1                                     2000000           2   
676      1                                     1100000           2   
677      1                                    21500000           2   
678      0                                     1000000           2   
679      1                                     2100000           2   
680      1     

In [274]:
trainData = df3[:180]

In [275]:
trainData

Satus  Amounts_raised_in_different_funding_rounds  Categories  \
0        1                                     1200000           2   
1        1                                     3000000           2   
2        1                                     7300000           1   
3        0                                     2000000           0   
4        1                                     1714000           6   
6        1                                     2400000           1   
7        1                                     3800000           1   
8        0                                     1300000           3   
9        0                                      740000           3   
10       1                                      535000           6   
11       1                                      750000           1   
12       1                                     1800000           3   
13       1                                     9400000           3   
14       1                                     2800000           0   
15       1                                     2400000           0   
19       1                                     2500000           1   
20       1                                     2800000           6   
21       1                                    11200000           0   
22       1                                     1200000           5   
23       1                                    39800000           0   
24       1                                      700000           6   
25       1                                     2380000           8   
26       1                                     1100000           4   
27       1                                   794820000           1   
28       0                                      875000           2   
29       1                                     5200000           6   
30       0                                    18250000           0   
31       1                                    11800000           6   
32       1                                     9720000           0   
33       0                                      500000           6   
..     ...                                         ...         ...   
194      1                                     3150000           3   
196      1                                      220000           0   
197      1                                     2000000           1   
198      0                                     1300000           1   
199      0                                     2515000           1   
200      1                                      850000           3   
202      1                                     1400000           4   
203      1                                    16615000           7   
204      1                                     6210000           1   
205      1                                      200000           3   
206      1                                       75000           3   
207      1                                     2100000           3   
208      1                                     1500000           3   
209      1                                     3017000           3   
210      1                                      800000           1   
211      1                                     1400000           4   
212      0                                     1315000           4   
213      1                                     1200000           0   
214      1                                    23600000           0   
215      1                                    12500000           5   
216      1                                     2064000           0   
218      1                                     4450000           0   
219      1                                    12200000           0   
223      1                                      500000           4   
224      1                                    12000000           6   
238      1     

In [276]:
features = trainData.values[:, :3]

In [277]:
a = trainData.values[:, 0:1]
targetlist = []
for i in range (0, 180):
    if (a[i] > 0):
        targetlist.append(1)
    else:
        targetlist.append(0)

In [278]:
targetarray = np.asarray(targetlist)
targetarray

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [279]:
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [280]:
clf.predict([[2., 2.]])

array([1])

In [281]:
clf.predict_proba([[2., 2.]])

array([[0., 1.]])

In [282]:
features

array([[         1,    1200000,          2],
       [         1,    3000000,          2],
       [         1,    7300000,          1],
       [         0,    2000000,          0],
       [         1,    1714000,          6],
       [         1,    2400000,          1],
       [         1,    3800000,          1],
       [         0,    1300000,          3],
       [         0,     740000,          3],
       [         1,     535000,          6],
       [         1,     750000,          1],
       [         1,    1800000,          3],
       [         1,    9400000,          3],
       [         1,    2800000,          0],
       [         1,    2400000,          0],
       [         1,    2500000,          1],
       [         1,    2800000,          6],
       [         1,   11200000,          0],
       [         1,    1200000,          5],
       [         1,   39800000,          0],
       [         1,     700000,          6],
       [         1,    2380000,          8],
       [  

In [283]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features[:180, :], targetarray[:180])

In [284]:
clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [285]:
with open('iris.dot', 'w') as f:
...     f = tree.export_graphviz(clf, out_file=f)

In [286]:
#from IPython.display import Image 
import os     
os.environ['PATH'] += os.pathsep + "C:/Users/ASUS-PC/Desktop/release/bin/"


In [287]:
import pydotplus
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = pydotplus.graph_from_dot_data(dot_data) 
graph.write_pdf('iris3.pdf')

True

In [288]:
feature_names = list(trainData.columns.values)

In [289]:
feature_names

['Satus',
 'Amounts_raised_in_different_funding_rounds',
 'Categories',
 'YCombinatorYear']

In [290]:
feature_names = feature_names[1:4]

In [291]:
#target_names = ['low', 'lower-intermediate', 'upper-intermediate', 'high']
target_names = ['Satus']
target_names = np.asarray(target_names)
target_names

array(['Satus'], dtype='|S5')

In [292]:
from IPython.display import Image  
dot_data = tree.export_graphviz(clf, out_file=None, feature_names=feature_names,  
                         class_names=target_names, filled=True, rounded=True, special_characters=True)  
graph = pydotplus.graph_from_dot_data(dot_data)  
Image(graph.create_png())  

IndexError: index 1 is out of bounds for axis 0 with size 1

In [293]:
features[0]
trainData[1:2]

Satus  Amounts_raised_in_different_funding_rounds  Categories  \
1      1                                     3000000           2   

   YCombinatorYear  
1             2013

In [294]:
clf.predict(features[1:4])

array([1, 1, 0])

In [295]:
testData = df3[180:]

In [296]:
testData

Satus  Amounts_raised_in_different_funding_rounds  Categories  \
251      1                                     4500000           8   
253      1                                      120000           8   
255      1                                      120000           0   
257      1                                     2025000           4   
258      1                                      622000           4   
259      1                                       15000           4   
264      1                                      289000           5   
267      1                                      120000           0   
269      1                                     1800000           6   
270      1                                    15000000           1   
272      1                                      120000           3   
275      1                                      120000           6   
277      1                                     2942000           6   
278      0                                       20000           6   
282      1                                      100000           0   
287      1                                      270000           1   
298      1                                       15000           4   
300      1                                      120000           0   
312      1                                     3300000           3   
314      1                                       20000           0   
319      1                                     1200000           1   
323      1                                      145000           5   
325      0                                       15000           0   
333      1                                      604000           8   
342      0                                      400000           0   
344      1                                     1500000           4   
357      1                                     1120000           8   
358      1                                      120000           0   
361      0                                       20000           0   
375      1                                       97000           5   
..     ...                                         ...         ...   
648      1                                     2000000           2   
649      1                                     1800000           2   
651      1                                     1300000           2   
652      0                                      890000           2   
654      1                                     6600000           2   
655      1                                     1200000           2   
656      1                                     2000000           2   
658      1                                      784000           2   
659      1                                      100000           2   
661      1                                     2000000           2   
662      1                                     5000000           2   
664      1                                     4777000           2   
665      1                                     6830000           2   
666      0                                     3000000           2   
668      1                                    19700000           2   
670      1                                     1670000           2   
671      1                                      920000           2   
672      0                                    39106000           2   
673      1                                      750000           2   
674      1                                       50000           2   
675      1                                     2000000           2   
676      1                                     1100000           2   
677      1                                    21500000           2   
678      0                                     1000000           2   
679      1                                     2100000           2   
680      1     

In [297]:
t_features = testData.values[:, :3]
testData

Satus  Amounts_raised_in_different_funding_rounds  Categories  \
251      1                                     4500000           8   
253      1                                      120000           8   
255      1                                      120000           0   
257      1                                     2025000           4   
258      1                                      622000           4   
259      1                                       15000           4   
264      1                                      289000           5   
267      1                                      120000           0   
269      1                                     1800000           6   
270      1                                    15000000           1   
272      1                                      120000           3   
275      1                                      120000           6   
277      1                                     2942000           6   
278      0                                       20000           6   
282      1                                      100000           0   
287      1                                      270000           1   
298      1                                       15000           4   
300      1                                      120000           0   
312      1                                     3300000           3   
314      1                                       20000           0   
319      1                                     1200000           1   
323      1                                      145000           5   
325      0                                       15000           0   
333      1                                      604000           8   
342      0                                      400000           0   
344      1                                     1500000           4   
357      1                                     1120000           8   
358      1                                      120000           0   
361      0                                       20000           0   
375      1                                       97000           5   
..     ...                                         ...         ...   
648      1                                     2000000           2   
649      1                                     1800000           2   
651      1                                     1300000           2   
652      0                                      890000           2   
654      1                                     6600000           2   
655      1                                     1200000           2   
656      1                                     2000000           2   
658      1                                      784000           2   
659      1                                      100000           2   
661      1                                     2000000           2   
662      1                                     5000000           2   
664      1                                     4777000           2   
665      1                                     6830000           2   
666      0                                     3000000           2   
668      1                                    19700000           2   
670      1                                     1670000           2   
671      1                                      920000           2   
672      0                                    39106000           2   
673      1                                      750000           2   
674      1                                       50000           2   
675      1                                     2000000           2   
676      1                                     1100000           2   
677      1                                    21500000           2   
678      0                                     1000000           2   
679      1                                     2100000           2   
680      1     

In [298]:
a = testData.values[:, 0:1]
t_targetlist = []
for i in range (0,108):
    if (a[i] > 0):
        t_targetlist.append(1)
    else:
        t_targetlist.append(0)

In [299]:
t_targetarray = np.asarray(t_targetlist)
t_targetarray

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [300]:
clf.score(features, targetarray)

1.0

In [301]:
clf.score(t_features, t_targetarray)

1.0

In [302]:
clf.predict(t_features[0:])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [303]:
clf.predict_proba(t_features[0:])

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.